//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_UOS_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Data
    {
        public int id { get; set; }
        public string TaskData { get; set; }
        public int Taskassign_fid { get; set; }
        public System.DateTime Submit_Date { get; set; }
    
        public virtual Task_Assign Task_Assign { get; set; }
    }
}
